runtime:
  container_commands:
  - apt update -y
  - apt install -y git
  python:
    python_version: '3.10'
    python_requirements: []
accelerators: []
accelerator_memory: null
pipeline_graph: my_pipeline:pipeline_graph
pipeline_name: null
