runtime:
  container_commands:
    - "apt update -y"
    - "apt install -y git"
    # - "apt-get update && \
    #   apt-get -y install gcc mono-mcs && \
    #   rm -rf /var/lib/apt/lists/*"
  python:
    python_version: "3.10"
    python_requirements:
      - "git+https://github.com/mystic-ai/pipeline.git@ph/just-balls-in-holes"
      - "FlagEmbedding==1.1.5"
accelerators:
  - cpu
pipeline_graph: "bge_base_en:bge_base_en"
pipeline_name: ross/bge-base-en
